# Generated by Django 4.0 on 2022-01-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
