# Generated by Django 4.0 on 2022-01-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forn', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='gmail',
        ),
    ]
